name: topic_be
description: An new Dart Frog application
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  dart_openai: ^2.0.1
  uuid: ^3.0.7
  dotenv: ^4.1.0
  dart_frog_web_socket: ^0.1.0-dev.3

  googleapis_auth: ^1.4.1
  firebase_dart: ^1.0.11
  web_socket_channel: ^2.0.0
  firedart: ^0.9.2

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
