name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - "release/*"

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.2
        with:
          channel: "stable"

      - name: Install dart_frog
        run: dart pub global activate dart_frog_cli

      - name: Install dependencies
        run: dart pub get

      - name: Run build
        run: dart_frog build

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

      - name: Get version from pubspec
        id: version
        run: |
          echo "::set-output name=version::$(grep 'version: ' pubspec.yaml | cut -d ' ' -f2)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build
          asset_name: build
          asset_content_type: application/zip

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build output
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Update Secrets
        run: |
          echo "${{ secrets.OPEN_AI_API_KEY }}" | gcloud secrets versions add "OPEN_AI_API_KEY" --data-file=-
          echo "${{ secrets.FIREBASE_API_KEY }}" | gcloud secrets versions add "FIREBASE_API_KEY" --data-file=-
          echo "${{ secrets.FIREBASE_PROJECT_ID }}" | gcloud secrets versions add "FIREBASE_PROJECT_ID" --data-file=-
          echo "${{ secrets.FIREBASE_APP_ID }}" | gcloud secrets versions add "FIREBASE_APP_ID" --data-file=-
          echo "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" | gcloud secrets versions add "FIREBASE_MESSAGING_SENDER_ID" --data-file=-

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy topic-be-unauthenticated \
            --source build \
            --region=us-central1
