name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - "unauthenticated/*"

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.2
        with:
          channel: "stable"

      - name: Install dart_frog
        run: dart pub global activate dart_frog_cli

      - name: Install dependencies
        run: dart pub get

      - name: Run build
        run: dart_frog build

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build output
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Update Secrets
        run: |
          echo "${{ secrets.OPEN_AI_API_KEY }}" | gcloud secrets versions add "OPEN_AI_API_KEY" --data-file=-
          echo "${{ secrets.FIREBASE_API_KEY }}" | gcloud secrets versions add "FIREBASE_API_KEY" --data-file=-
          echo "${{ secrets.FIREBASE_PROJECT_ID }}" | gcloud secrets versions add "FIREBASE_PROJECT_ID" --data-file=-
          echo "${{ secrets.FIREBASE_APP_ID }}" | gcloud secrets versions add "FIREBASE_APP_ID" --data-file=-
          echo "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" | gcloud secrets versions add "FIREBASE_MESSAGING_SENDER_ID" --data-file=-
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy topic-be-unauthenticated \
            --source build \
            --region=us-central1 \
            --allow-unauthenticated
